### ISSUE TITLE
Comments and Revisions

### ISSUE THREAD

**Issue by tjburch** [matthewfeickert/talk-Argonne-lunch-seminar#1]
Hi Matthew - figured I would put comments and notes here.

3: I'd maybe emphasize 2 extra things, order of magnitude of model parameters (inc systematics) and what "time to fit" encompasses (parameter estimation via sampling using grid computation). 

The switch from slide 3-4 is also a bit of a hard segue, just something to watch out for (eventually remedied with the case study though) - maybe explain why differentiation is useful for inference.

8-10 look good, gives a good background to old HF

12: I think I'd personally avoid ML in the title of this slide and just say they're "industry tools" and mabe put "generally developed for ML applications, but widely applicable" just to not scare off people who have their ML hesitancy.

13: Even with the zoom in, this DAG is going to be tough to see... anyway to make it still bigger?

Examples shown are great, super useful. If a little time-crunched, you could move quickly through the cut-based example

28: These are a bunch of cool new tools with fancy new names, which means a lot of people are going to immediately tune out. Maybe you could put like the "old" equivalent of the pipeline for analogy? 

33-34: Is the GPU implementation vendor-specific or does it work with intel, nvidia, amd, etc

General:

I think the balance between subjects is good. If you're looking to add, I might do more on the second half, the autodiff stuff seems relatively complete (answered most of my immediate questions).

I mentioned earlier, but I think one concern is that with the slew of new tool names, it's easy for someone not steeped in this ecosystem to get a bit lost, so as many sort of reminders (verbally or text) would probably help keep on track

Otherwise, great slides! Looks like it'll be a good talk, excited to hear it.

**Comment by matthewfeickert** [comment]
Thanks so much for the early feedback, @tjburch! I really appreciate it. :)


> 3: I'd maybe emphasize 2 extra things, order of magnitude of model parameters (inc systematics) and what "time to fit" encompasses (parameter estimation via sampling using grid computation).

Should be addressed a bit better now.
 
> The switch from slide 3-4 is also a bit of a hard segue, just something to watch out for (eventually remedied with the case study though) - maybe explain why differentiation is useful for inference.

Yup. This was on the "todo" docket tonight, and I added a few motivation slides.


> 12: I think I'd personally avoid ML in the title of this slide and just say they're "industry tools" and mabe put "generally developed for ML applications, but widely applicable" just to not scare off people who have their ML hesitancy.

Noted and resolved.
 
> 13: Even with the zoom in, this DAG is going to be tough to see... anyway to make it still bigger?

I'd normally work to make this more readable, but the majority of the graph doesn't need to be read but more just indicate to people the nature of what's happening.

> Examples shown are great, super useful. If a little time-crunched, you could move quickly through the cut-based example

:+1: 

> 28: These are a bunch of cool new tools with fancy new names, which means a lot of people are going to immediately tune out. Maybe you could put like the "old" equivalent of the pipeline for analogy?

Hm. I'll think on that tonight. I won't spend much time on that slide, but I think part of the reason why we have the IRIS-HEP AS group is that Run 2 style pipelines didn't really exist in any clean sort of format for end to end analysis that was recognizable outside of specific working groups.

> 33-34: Is the GPU implementation vendor-specific or does it work with intel, nvidia, amd, etc

It depends on the workload/libraries you want to run. But I welcome that as a question during the talk so that I have an excuse to expand on it. :wink: 

> I mentioned earlier, but I think one concern is that with the slew of new tool names, it's easy for someone not steeped in this ecosystem to get a bit lost, so as many sort of reminders (verbally or text) would probably help keep on track

This is very useful, especially given that I am too steeped in this stuff. I'll ask the audience to interrupt me if I start going off talking in jargon they don't understand, but I'll work to be extra conscious of when I am touching on new topics.

**Comment by tjburch** [comment]
Since you asked for the nitty-gritty :)

8 - seems to give the plan before the why and how, maybe move point 2 (replace non-differentiable) to the end. The first point also seems incomplete (mabye "Allows us to write fully differentiable programs that are both efficent and accurate" to tie back to earlier point)

11 - The binned SUSY analysis example here is good but also make sure you mention how this works running HF along a mass spectra like the SM plot you show in the prior slide (especially wrt correlated uncertainties)

12 - I know you and I love pure python, but how does this matter to others? (e.g. does getting it into pure python only make it useful for non-ROOT HEP analyses? Or theoretically any science/statistics domain? just a thought)

13 - could you bump up font size on the sub-bullets? lots of white space

14 -
 The "autodiff" abbreviation has already been defined a few times, either just use it or write out automatic differentiation. 
"As huge buy in" reads strange to me - "Due to huge buy in...?" 
Same with "Show hardware acceleartion giving" - "Hardware acceleration shows an order of magnitude...?"
What is "traditional" in the slide

19 - I'm sure you're normalizing the histograms here between the left and the right, so being **_way_ too overly** pedantic, they probably both wouldn't be a "Yield." One could be "Normalized Yield" or "AU" or whatever

25 - do you have a 2D example plot for cuts? That might drive home the point of your third point here. I'm also not positive how the 4th point (Allows cut to be a tunable parameter) varies from the traditional significance scan?

26 - is this figure yours? I would recommend making the grey flow arrows like 3x the boldness, otherwise, they get lost in some of the other arrows

Take or reject any/all of these, won't be offended either way, mostly style/semantics :) I personally always feel like too much feedback is the right amount of feedback, that way I can decide what's useful.

**Comment by tjburch** [comment]
(Just minor edited my comment on slide 8, first sentence was a weird joining of a couple that didn't make any sense, meaning I should probably go to bed)
